# Generated by Django 5.2.5 on 2025-08-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название блюда на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название блюда на узбекском')),
                ('category', models.CharField(choices=[('first', 'Первые блюда'), ('second', 'Вторые блюда'), ('dessert', 'Десерты'), ('drink', 'Напитки')], max_length=10, verbose_name='Категория блюда')),
                ('description_ru', models.TextField(verbose_name='Описание блюда на русском')),
                ('description_uz', models.TextField(verbose_name='Описание блюда на узбекском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Картинка блюда')),
                ('video', models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Видео блюда')),
                ('recipe_text', models.TextField(verbose_name='Текст рецепта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена рецепта')),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='products/recipe_images/', verbose_name='Доп. картинка рецепта')),
                ('recipe_video', models.FileField(blank=True, null=True, upload_to='products/recipe_videos/', verbose_name='Доп. видео рецепта')),
                ('recipe_file', models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Доп. файл рецепта')),
                ('recipe_source_link', models.URLField(blank=True, null=True, verbose_name='Доп. ссылка рецепта')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID пользователя')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbek')], default='ru', max_length=2, verbose_name='Выбранный язык')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Квитанция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile')),
            ],
            options={
                'verbose_name': 'История покупок и квитанции',
                'verbose_name_plural': 'Истории покупок и квитанций',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
