# Generated by Django 5.2.5 on 2025-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe_text_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Текст рецепта на узбекском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_text',
            field=models.TextField(verbose_name='Текст рецепта на русском'),
        ),
    ]
